### ISSUE TITLE
SVG extrusion error

### ISSUE THREAD

**Issue by JansenSmith** [NeuronRobotics/JCSG#43]
Unsure what issue in geometry is causing this error, in https://github.com/JansenSmith/SDXLvoucher
Issue arises when I try to extrude text (rendered as paths) and when I separated the lightbulb element into multiple geometries.

Skip Writing file contents, file is same
Extruding SVG C:\Users\Jansen\Documents\bowler-workspace\gitcache\github.com\JansenSmith\SDXLvoucher\JanKal_SDXLvoucher.svg
Layers= [Border, Danyel, Emblem, Jansen, Lines, Text, Ticket]
script error
java.lang.Exception: javax.vecmath.SingularMatrixException: cannot invert matrix
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingFileWidget$3.run(ScriptingFileWidget.java:471)
Caused by: javax.vecmath.SingularMatrixException: cannot invert matrix
	at javax.vecmath.Matrix4d.invertGeneral(Matrix4d.java:1996)
	at javax.vecmath.Matrix4d.invert(Matrix4d.java:1951)
	at eu.mihosoft.vrl.v3d.Transform.inverse(Transform.java:594)
	at eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(PolygonUtil.java:143)
	at eu.mihosoft.vrl.v3d.ext.org.poly2tri.PolygonUtil.concaveToConvex(PolygonUtil.java:111)
	at eu.mihosoft.vrl.v3d.Extrude$1.monotoneExtrude(Extrude.java:89)
	at eu.mihosoft.vrl.v3d.Extrude$1.extrude(Extrude.java:82)
	at eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayers(SVGLoad.java:690)
	at eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayerToCSG(SVGLoad.java:656)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at JanKal_SDXLvoucher.run(JanKal_SDXLvoucher.groovy:31)
	at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inline(GroovyHelper.java:61)
	at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inlineScriptRun(GroovyHelper.java:81)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:449)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:999)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingFileWidget$3.run(ScriptingFileWidget.java:430)

**Comment by madhephaestus** [comment]
the imported SVG does not comply with SVG convention. To fix, rotate the lightbulb tick marks slightly.

**Comment by madhephaestus** [comment]
@JansenSmith lmk if that fixes it for you?
