### ISSUE TITLE
Krita vector layers 

### ISSUE THREAD

**Issue by JansenSmith** [NeuronRobotics/JCSG#62]
Compatibility issue w Krita vector layers:

```
java.lang.NumberFormatException: For input string: "180pt"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.toPx(SVGLoad.java:89)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.toMM(SVGLoad.java:110)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.loadAllGroups(SVGLoad.java:295)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.toPolygons(SVGLoad.java:259)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayers(SVGLoad.java:690)
at eu.mihosoft.vrl.v3d.svg.SVGLoad.extrudeLayerToCSG(SVGLoad.java:666)
at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
at TechOrnament.run(TechOrnament.groovy:68)
at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inline(GroovyHelper.java:58)
at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inlineScriptRun(GroovyHelper.java:78)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:522)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:1115)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingFileWidget$3.run(ScriptingFileWidget.java:582)
java.lang.RuntimeException: Please fix me! I don't know what to do?
at eu.mihosoft.vrl.v3d.Node.invert(Node.java:140)
at eu.mihosoft.vrl.v3d.CSG._unionNoOpt(CSG.java:1093)
at eu.mihosoft.vrl.v3d.CSG._unionIntersectOpt(CSG.java:1070)
at eu.mihosoft.vrl.v3d.CSG._differenceCSGBoundsOpt(CSG.java:1262)
at eu.mihosoft.vrl.v3d.CSG.difference(CSG.java:1235)
at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
at TechOrnament.run(TechOrnament.groovy:70)
at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inline(GroovyHelper.java:58)
at com.neuronrobotics.bowlerstudio.scripting.GroovyHelper.inlineScriptRun(GroovyHelper.java:78)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:522)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:1115)
at com.neuronrobotics.bowlerstudio.scripting.ScriptingFileWidget$3.run(ScriptingFileWidget.java:582)
Extruding outline SVG /home/jansen/Documents/bowler-workspace/gitcache/github.com/JansenSmith/TechOrnament/TechOrnament_outline.svg
```

**Comment by madhephaestus** [comment]
@JansenSmith you could likely fix this one if you wanted to take a look.
